---
title: "APcalc V2"
output: html_document
---

```{r}
#library setup
library(rms)
library(survival)
library (tidyr)
library(dplyr)
library(lazyeval)
library (readr)
library (survminer)
library (ComplexHeatmap)
library (ggfortify)
library (beeswarm)
library (stringr)
library(reshape2)
library(circlize)
library(ggbiplot)
library(ape)
library(RColorBrewer)
library(ggplot2)
library(beeswarm)
library(ggrepel)
library(ggbeeswarm)
library(ggrastr)
library(treemap)
library(igraph)
library(data.table)
library(APcalc)
library(GenomicAlignments)
#setwd ("C:/Users/sundarraghav/Desktop/PhD/APIO/AP Validation/APCalc/")

set.seed(20190209)

```

```{r Annals_intersectBed}

# Test using files from Annals paper

# Make coverage file 
aditicoverage <- createCoverageMatrix(inputPath = "test/Annals/Annals/", 
                                      filePattern = "_WTS.bed", 
                                      junctionReads = F, 
                                      normalize = T, 
                                      librarySizeFile ="test/Annals/Annals/annalslibsizes.txt")

# Make readcount matrix same as promoters

promoters <- read.table("test/Annals/Annals/promoterregions.txt", stringsAsFactors = F, sep="\t", header=F)
promoters <- promoters[!duplicated(promoters$V9),]
rownames(promoters) <- promoters$V9
promoters <- promoters[rownames(aditicoverage),]

# Calculate AP score
aditiapscore <- calculateAlternatePromoterScore(aditicoverage, 
                                                promoters$V5, 
                                                promoterMethod = "medianbased", 
                                                medianThreshold = 4)

# Check survival
clindata <- read.table(file = "test/clinicaldata.csv", sep=",", stringsAsFactors = F, header=T)
covpb <- read.table("test/Annals/Annals/covpb.txt", header = F, stringsAsFactors = F, sep="\t" )
covpb <- rename(covpb, V2 = "pbid", V1 = "id" )
clindata <- rename(clindata, id = "pbid")

# Left join was not working because the id in aditiapscore and covbp was not same. 

# fixing that
covpb$id <- gsub("_RC_", "_RC", covpb$id)
covpb$id <- gsub("_RT_", "_RT", covpb$id)

annalsapscore <- left_join(aditiapscore, covpb, by = "id" )
annalsapscore <- left_join(annalsapscore, clindata, by = "pbid")

# keep only samples for which clinical data is available
alternatePromoterScore <- annalsapscore[,1:2]
clinicaldata <- annalsapscore[,c(1,5,6)]
clinicaldata$survtime <- as.numeric(clinicaldata$survtime)

annalssurvival <- calculateSurvival(alternatePromoterScore = alternatePromoterScore, 
                                    clinicaldata = clinicaldata, 
                                    survivalTime = clinicaldata$survtime, 
                                    survivalEvent = clinicaldata$status,
                                    alternatePromoterQuantileThreshold = 0.66, 
                                    title = "AP Group -  66/33 Split")
```


```{r annals_junction}

# Test using files from Annals paper

# Make coverage file  

#This commented code this will nto work as is because the name in library size file is not # the same as the junction files. Made a new lib file

# aditicoverage <- createCoverageMatrix(inputPath = "test/Annals/Annals/", 
#                                       filePattern = "_WTS.bam", 
#                                       junctionReads = T, 
#                                       junctionType = "tophat", 
#                                       promoterFile = "test/Annals/Annals/promoterregions.txt", 
#                                       normalize = T, 
#                                       librarySizeFile ="test/Annals/Annals/annalslibsizes.txt")

aditicoverage <- createCoverageMatrix(inputPath = "test/Annals/Annals/", 
                                      filePattern = "_WTS.bam", 
                                      junctionReads = T, 
                                      junctionType = "tophat", 
                                      promoterFile = "test/Annals/Annals/promoterregions.txt", 
                                      normalize = T, 
                                      librarySizeFile ="test/Annals/Annals/annalslibsizes_junction.txt")


# Make readcount matrix same as promoters

promoters <- read.table("test/Annals/Annals/promoterregions.txt", stringsAsFactors = F, sep="\t", header=F)
promoters <- promoters[!duplicated(promoters$V9),]
rownames(promoters) <- promoters$V9
promoters <- promoters[rownames(aditicoverage),]

# Calculate AP score
aditiapscore <- calculateAlternatePromoterScore(aditicoverage, 
                                                promoters$V5, 
                                                promoterMethod = "medianbased", 
                                                medianThreshold = 4)

# Check survival
clindata <- read.table(file = "test/clinicaldata.csv", sep=",", stringsAsFactors = F, header=T)
covpb <- read.table("test/Annals/Annals/covpb.txt", header = F, stringsAsFactors = F, sep="\t" )
covpb <- rename(covpb, V2 = "pbid", V1 = "id" )
clindata <- rename(clindata, id = "pbid")

# Left join was not working because the id in aditiapscore and covbp was not same. 

# fixing that
covpb$id <- gsub("Coverage_alternate_","",gsub("_RT_", "_RT.bed", gsub("_RC_", "_RC.bed", covpb$id)))
annalsapscore <- left_join(aditiapscore, covpb, by = "id" )
annalsapscore <- left_join(annalsapscore, clindata, by = "pbid")

# keep only samples for which clinical data is available
alternatePromoterScore <- annalsapscore[,1:2]
clinicaldata <- annalsapscore[,c(1,5,6)]
clinicaldata$survtime <- as.numeric(clinicaldata$survtime)

annalssurvival <- calculateSurvival(alternatePromoterScore = alternatePromoterScore, 
                                    clinicaldata = clinicaldata, 
                                    survivalTime = clinicaldata$survtime, 
                                    survivalEvent = clinicaldata$status,
                                    alternatePromoterQuantileThreshold = 0.66, 
                                    title = "AP Group -  66/33 Split")
```


```{r gemini_junction}

# this was not working because the name of files in libsize file was not same as the files in the inputpath. made a v2

aditicoverage <- createCoverageMatrix(inputPath = "test/Gemini/Gemini/Junctional/", 
                                      filePattern = ".out.tab", 
                                      junctionReads = T, 
                                      junctionType = "star", 
                                      promoterFile = "test/Annals/Annals/promoterregions.txt", 
                                      normalize = T,  librarySizeFile="test/Gemini/Gemini/Coverage/geminilibsizes_v2.txt")

# promoters <- read.table("promoterregions.txt", stringsAsFactors = F)
# rownames(promoters) <- promoters$V9
# promoters <- promoters[rownames(aditicoverage),]
# 
# aditiapscore <- calculateAlternatePromoterScore(aditicoverage, promoters$V5, promoterMethod = "medianbased", medianThreshold = 4)

```

